#!/bin/sh

# Note: Default area 0 0 10208 7424

DEVICE_STYLUS="Wacom Graphire4 4x5 Pen stylus"
DEVICE_ERASER="Wacom Graphire4 4x5 Pen eraser"
DEVICE_CURSOR="Wacom Graphire4 4x5 Pen cursor"
DEVICE_PAD="Wacom Graphire4 4x5 Pad pad"

AREA_169="0 0 10208 5742"
AREA_1610="0 0 10208 6380"
AREA_54="464 0 9744 7424"

AREA_DVI0=$AREA_1610
AREA_DVI1=$AREA_1610

function select_output_dvi0 {
    xsetwacom set "$DEVICE_STYLUS" MapToOutput DVI-0
    xsetwacom set "$DEVICE_ERASER" MapToOutput DVI-0
    xsetwacom set "$DEVICE_STYLUS" Area $AREA_DVI0
    xsetwacom set "$DEVICE_ERASER" Area $AREA_DVI0
}

function select_output_dvi1 {
    xsetwacom set "$DEVICE_STYLUS" MapToOutput DVI-1
    xsetwacom set "$DEVICE_ERASER" MapToOutput DVI-1
    xsetwacom set "$DEVICE_STYLUS" Area $AREA_DVI1
    xsetwacom set "$DEVICE_ERASER" Area $AREA_DVI1
}

if [ "$1" = "--swap-output" ]; then
    if [ -d "$XDG_RUNTIME_DIR" ]; then
        mkdir "$XDG_RUNTIME_DIR/wacomctl"
    else
        select_output_dvi0
        exit
    fi

    if [ -f "$XDG_RUNTIME_DIR/wacomctl/secondary" ]; then
        select_output_dvi0
        rm "$XDG_RUNTIME_DIR/wacomctl/secondary"
    else
        select_output_dvi1
        touch "$XDG_RUNTIME_DIR/wacomctl/secondary"
    fi
    exit
fi

# fall back to first output
select_output_dvi0

# absolute mode
xsetwacom set "$DEVICE_STYLUS" Mode Absolute
xsetwacom set "$DEVICE_ERASER" Mode Absolute

# change middle and right button
xsetwacom set "$DEVICE_STYLUS" Button 2 3
xsetwacom set "$DEVICE_STYLUS" Button 3 2

# click on tap
xsetwacom set "$DEVICE_STYLUS" TabletPCButton on

# button for output switch: emulate meta4+f12
xsetwacom set "$DEVICE_PAD" button 9 "key +super f12 -super"
