#!/bin/sh

# Note: Default area 0 0 10208 7424

DEVICE_STYLUS="Wacom Graphire4 4x5 stylus"
DEVICE_ERASER="Wacom Graphire4 4x5 eraser"
DEVICE_CURSOR="Wacom Graphire4 4x5 cursor"
DEVICE_PAD="Wacom Graphire4 4x5 pad"

AREA_DVI0="0 0 10208 5742"
AREA_DVI1="464 0 9744 7424"

function select_output_dvi0 {
    xsetwacom set "$DEVICE_STYLUS" MapToOutput DVI-0
    xsetwacom set "$DEVICE_ERASER" MapToOutput DVI-0
    xsetwacom set "$DEVICE_STYLUS" Area $AREA_DVI0
    xsetwacom set "$DEVICE_ERASER" Area $AREA_DVI0
}

function select_output_dvi1 {
    xsetwacom set "$DEVICE_STYLUS" MapToOutput DVI-1
    xsetwacom set "$DEVICE_ERASER" MapToOutput DVI-1
    xsetwacom set "$DEVICE_STYLUS" Area $AREA_DVI1
    xsetwacom set "$DEVICE_ERASER" Area $AREA_DVI1
}

if [ "$1" = "--swap-output" ]; then
    if [ "$(xsetwacom get "$DEVICE_STYLUS" Area)" = "$AREA_DVI1" ]; then
        select_output_dvi0
    else
        select_output_dvi1
    fi
    exit
fi

# fall back to first output
select_output_dvi0

# absolute mode
xsetwacom set "$DEVICE_STYLUS" Mode Absolute
xsetwacom set "$DEVICE_ERASER" Mode Absolute

# change middle and right button
xsetwacom set "$DEVICE_STYLUS" Button 2 3
xsetwacom set "$DEVICE_STYLUS" Button 3 2

# click on tap"
xsetwacom set "$DEVICE_STYLUS" TabletPCButton on

# button for output switch: emulate meta4+f12
xsetwacom set "$DEVICE_PAD" button 9 "key +super f12 -super"
